# Generated by Django 3.1 on 2020-09-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('imageURL', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('iconLink', models.URLField()),
                ('toolLink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('imageURL', models.URLField()),
                ('dscription', models.TextField(max_length=1024)),
                ('githublink', models.URLField()),
                ('youtubelink', models.URLField()),
                ('tools', models.ManyToManyField(related_name='projects', to='portfolio.tool')),
            ],
        ),
    ]
