# Generated by Django 3.1 on 2020-09-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200929_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='course', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='githublink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='youtubelink',
            field=models.URLField(null=True),
        ),
    ]
