# Generated by Django 3.1 on 2020-09-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200930_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='type',
            field=models.CharField(blank=True, choices=[('PL', 'programing language'), ('TL', 'tool')], default='PL', max_length=2),
        ),
    ]
