# Generated by Django 3.1 on 2020-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_tool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(default='weuygdjhagl asdhakjshdl sdhsalasdas'),
            preserve_default=False,
        ),
    ]
