# Generated by Django 3.1 on 2020-10-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=64)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('certificate', models.URLField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='certificate',
        ),
    ]
