# Generated by Django 3.1 on 2020-10-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20201002_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='importancy',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='importancy',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
    ]
