# Generated by Django 3.1 on 2020-10-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20201010_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('icon', models.URLField()),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
